---
- name: Install cleanup grid accounts package
  package:
    name: cleanup-grid-accounts
    state: present

- name: Configure cleanup grid accounts package
  template:
    src: cleanup-grid-accounts.conf.j2
    dest: /etc/cleanup-grid-accounts.conf

- name: Cron job for account cleanup
  cron:
    name: cleanup grid accounts
    minute: "{{ 59 | random(seed=inventory_hostname) }}"
    hour: "*/6"
    job: >
      /usr/sbin/cleanup-grid-accounts.sh 2>&1
      >> /var/log/cleanup-grid-accounts.log
- name: logrotate for the cron job
  copy:
    content: |
      {{ ansible_managed | comment }}
      /var/log/cleanup-grid-accounts.log {
        weekly
        rotate 30
        missingok
        compress
        copytruncate
      }
    dest: /etc/logrotate.d/cleanup-grid-accounts
