---
# tasks file for hephyvienna.poolaccounts
- name: Create gridmapdir
  file:
    path: /etc/grid-security/gridmapdir
    state: directory

- name: Create groups for the poolaccounts
  group:
    name: "{{ item.group }}"
    gid: "{{ item.gid }}"
  loop: "{{ poolaccounts }}"
  loop_control:
    label: "{{ item.group }}"

- name: Create poolaccounts
  include_tasks: poolaccount.yml
  loop: "{{ poolaccounts }}"
  loop_control:
    loop_var: account

- name: Cleanup grid accounts
  include_tasks: cleanup-grid-accounts.yml
  when: poolaccounts_enable_cleanup

- name: Enable grid-mapfile
  template:
    src: grid-mapfile.j2
    dest: /etc/grid-security/grid-mapfile
