---
- name: Create a range of user accounts
  user:
    name: "{{ account.name | format(idx+1) }}"
    comment: "{{ account.comment | default('') }}"
    uid: "{{ account.uid + idx * (account.step | default(1)) }}"
    group: "{{ account.group }}"
    groups: "{{ account.groups | default([]) }}"
    home: "{{ poolaccounts_homedir + '/' + (account.name | format(idx) ) }}"
  loop: "{{ range(account.number) | list }}"
  loop_control:
    label: "{{ account.name | format(idx+1) }}"
    index_var: idx
  when: account.number is defined

- name: Create a single user account
  user:
    name: "{{ account.name }}"
    comment: "{{ account.comment | default('') }}"
    uid: "{{ account.uid }}"
    group: "{{ account.group }}"
    groups: "{{ account.groups | default([]) }}"
    home: "{{ poolaccounts_homedir + '/' + account.name }}"
  when: account.number is not defined
